### ISSUE TITLE
Ruby master make install isn't installing power_assert

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/power_assert#51]
See https://bugs.ruby-lang.org/issues/20560

`make install` is not installing `power_assert`.  The problem seems to be a version mismatch between the main/master branch here and Ruby's [gems/bundled_gems](https://github.com/ruby/ruby/blob/c3b5b98e15e9a893aaca46e53d2c8931bf13e322/gems/bundled_gems).

Also, current version is `2.0.4dev`.  I believe a proper 'Semantic versioning 2.0' string would be `2.0.4-dev`?

Can someone please fix this?

I hope people want third parties to test against Ruby head/master.  A missing gem may break their CI, and discourage them from testing with it.

I don't mean to imply fault. I would just like to see it fixed...

**Comment by Maumagnaguagno** [comment]
I keep seeing the following error with Ruby head and GitHub Actions, which I believe is related to this  issue.
Previous versions of Ruby execute the same tests without errors.

```
/home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/rubygems/specification.rb:1417:in 'block in Gem::Specification#activate_dependencies': Could not find 'power_assert' (>= 0) among 85 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/runner/.local/share/gem/ruby/3.4.0+0:/home/runner/.rubies/ruby-head/lib/ruby/gems/3.4.0+0' at: /home/runner/.rubies/ruby-head/lib/ruby/gems/3.4.0+0/specifications/test-unit-3.6.2.gemspec, execute `gem env` for more information
```
