### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Nakilon** [ruby/power_assert#52]
README does not seem to show how to make `assert` an accessible method.
And I can't find the method `assert` in repo.
```ruby
source "https://rubygems.org"
gem "rake"
gem "power_assert"
```
```ruby
task :default do
  require "power_assert"
  assert do
    1 == 2
  end
end
```
```none
NoMethodError: undefined method `assert' for main:Object
```
ruby 2.6.6

**Comment by hsbt** [comment]
See https://test-unit.github.io/test-unit/en/Test/Unit/Assertions.html#assert-instance_method
